### ISSUE TITLE
Repo moved?

### ISSUE THREAD

**Issue by DomT4** [swift-nav/libswiftnav-legacy#370]
Hey folks,

Can someone confirm whether this repo was formerly `https://github.com/swift-nav/libswiftnav/`? There's a Homebrew formula for `libswiftnav` and our update checking script failed to locate a URL to check against earlier, which led to some manual investigation.

Assuming it was a relocation from one repo to another, that has resulted in the checksum changing on the archive tarballs. `v0.21.tar.gz` was previously `99e7ac3f190d76b2c1ceb17dae76d24b86d1a71501db4f6a49759539bb393756` and is now `087c7264c0d0d735414f8bffbfa52ab44696c500ba14a43262d98d6aa093221f`, so it'd be good to have confirmation there's nothing nefarious in that so I we can update the URL/checksum in Homebrew. Thanks!

**Comment by anth-cole** [comment]
@DomT4 - That's correct - this is the same repo renamed to `libswiftnav-legacy` should be no problem just updating the link.

**Comment by DomT4** [comment]
Thanks for the confirmation!
